export const emptyBook = {
  isbn: '',
  title: '',
  series: '',
  author_fname: '',
  author_lname: '',
  rating: '',
  length: '',
  release_date: '',
  thumbnail: '',
  blurb: '',
  source: '',
  note: '',
  is_purchased: false,
  is_prioritized: false,
};
